CATEGORY=((0,'All'),
		(1,'Academics & Professional'),
		   (2,'Literature - Fiction & Non-Fiction'),	
	)
AGEGROUP=((0, 'Not Available'),
	(1,'0-2 Years'),
	(5,'3-4 Years'),
	(10,'5-8 Years'),
	(20,'9-11 Years'),
	(50,'Teen'),
	(100,'Young Adult'),
	)

GENRE = ((0, 'Fiction'),
		(1,'Action and Adventure'),
		(5,'Crime,Thriller & Mystery'),
		(10,'Comics'),
		(20,'Romance'),
		(50,'Fantasy,Horror& Sci-Fi'),
		(100,'Biographies'),
		(200,'History'),
		(500,'Science & Technology'),
		(1000,'Travel'),
		(2000,'Humour'),
	)
TAG = ((0, 'Not Available'),
		(1,'Science & Mathematics'),
		(5,'School Textbooks & Guides'),
		(10,'Computer Science'),
		(20,'Engineering'),
		(50,'Law'),
		(100,'Business SelfHelp'),
		(200,'Business Strategy'),
		(500,'Economics'),
		(1000,'Industries & Sectors'),
		(2000,'Health & Family Development'),
	)
CARTSTATUS=((1,'Wishlist'),
	(5,'Ordered'),
	(10,'Paid'),
	(20,'Delivered'),
	)
